### ISSUE TITLE
Command injection via SecureDatum

### ISSUE THREAD

**Issue by hackjammer** [gaelcolas/Datum#17]
This code is vulnerable to command injection from the data:
https://github.com/gaelcolas/Datum/blob/master/Datum/classes/SecureDatum.ps1#L44

e.g.
```powershell
PS C:\> $datum = @{normal=1;evil='[ENC=s";Write-Host "HACKED";$e="]'} | ConvertTo-ProtectedDatum -UnprotectOptions @{ClearTextPassword='doesntmatter'}
PS C:\> $datum
HACKED
HACKED

normal evil
------ ----
     1
```

This is not great, there are cases where config data will be updated by less trusted persons - and that should not result in execution on the build machine. A quick fix may be to be more explicit with your regex to only accept base64 data but I'm not sure it should be relied on.

**Comment by gaelcolas** [comment]
I agree this is less than ideal, but securing code execution from the Secure Config Data is low on the priority list for now, here's why:
- compromised config Data in the end means compromised systems
- SecureDatum does not seem to be compatible with PS Core (because ProtectedData is not) so it should most likely live outside of the 'core' Datum module as an option
- a way to secure this could be by using a constrained endpoint like Plaster where only a subset of commands is allowed (that's a bit of work).

Thanks for putting on the list, but it probably won't make the cut for v1.0.

**Comment by gaelcolas** [comment]
The new way the ProtectedDatum works (via Data handlers) should fix that somehow.
It does not rely on the SecureDatum class anymore, and this approach will be dropped very soon.

Data handlers are much easier to use, and can be external modules (so it's the users responsibility to review those).

There's still ways of 'injecting' code via the Datum.yml, by using scriptblocks in `<%= %>` in the ResolutionPrecedence paths.
