### ISSUE TITLE
Build new mof files only if the specific role or server configuration changed

### ISSUE THREAD

**Issue by Outek** [gaelcolas/Datum#58]
It would be nice, if there is a stage or task to build only the modified server configurations or all affected servers from a role.

Server1 - role appserver
Server2 - role appserver
Server3- role webserver

Change server1.yaml -> new *.mof for Server1  
Change of role appserver -> new *.mof for Server1 and Server2

Is there an easy way to do this?

**Comment by raandree** [comment]
Have a look at the [DscWorkshop](https://github.com/AutomatedLab/DscWorkshop) project. The build process does not detect changes automatically but offers a filter:

``` PowerShell
.\Build.ps1 -Filter { $_.NodeName -eq 'DSCFile01' }
.\Build.ps1 -Filter { $_.Role -eq 'WebServer' }
```

Is this what you are looking for?

**Comment by Outek** [comment]
Yes, probably. I think i‘ll do something like git diff head —name-only and pass this files to the filter.

**Comment by gaelcolas** [comment]
Bear in mind that it's risky doing so this way. It's dependent upon your hierarchy, so if you change a location file for instance, you need to find the relationship to the nodes, and that applies for every layers.
That's why I was experimenting with #55, and there's more do do with diffing the RSOP to see what actually changed.
